
name: ⚙️ Notify Python Datapack

on:
  release:
    types: [published]

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Get release version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create issue
        uses: peter-evans/create-issue-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: Stoupy51/python_datapack
          title: "⚙️ ci: [Bookshelf] New version ${{ steps.get_version.outputs.VERSION }}"
          body: |
            A new version of Bookshelf has been released: ${{ steps.get_version.outputs.VERSION }}
            
            Check out the release at: https://github.com/${{ github.repository }}/releases/tag/${{ steps.get_version.outputs.VERSION }}

